#version 450 core
/**
 * \file simple.comp
 * \author Seungheon Jeon
 * \date 2024 Spring
 * \par CS250 Computer Graphics II
 * \copyright DigiPen Institute of Technology
 */
layout (local_size_x = 32, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, rgba8) uniform image2D output_image;

void main()
{
    imageStore(output_image, ivec2(gl_GlobalInvocationID.xy),
               vec4(vec2(gl_LocalInvocationID.xy) / vec2(gl_WorkGroupSize.xy), 0.0, 0.0));
}